version: '3.8'
services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbpg001
    ports:
      - '5432:5432'

  api:
    image: demo_auto
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbpg001
      - CLIENT_URL
    depends_on:
      - db
    ports:
      - '8090:8090'

